---
output: pdf_document
---
\doublespacing
\begin{center}
Towards a Framework for Operational Risk \\ 
in the Banking Sector \\
\vspace{12pt}
by \\
\vspace{12pt}
Mphekeleli Hoohlo \\
University of the Witwatersrand, 2019
\end{center}

\vspace{12pt}

\singlespacing
\noindent Major Professor: Eric Schaling, Ph.D.

\noindent Department: Law, Commerce \& Management

\vspace{12pt}

\doublespacing
Researchers in health and prevention are increasingly interested in, not only *if* one variable affects another, but *how* the effect takes place. Mediation analysis is built for this very question. However, it lacks interpretable effect size estimates in situations where the mediator (intermediate variable) and/or the outcome is categorical or otherwise far from normally distributed. By integrating a powerful approach known as average marginal effects within mediation analysis---termed *Marginal Mediation Analysis* (MMA)---the issues regarding categorical mediators and/or outcomes is, in large part, resolved. The project discussed herein presents the development, evaluation, and application of this novel approach to understand its utility to researchers. The aims of this project were four-fold: 1) develop MMA and the software to perform it, 2) test its accuracy, robustness, and coverage via Monte Carlo simulations and develop guidelines for MMAs use, and 4) apply it to real prevention science data. 

First, MMA is built on generalized linear modeling and is available in R as the `MarginalMediation` package. Second, Monte Carlo simulations were used to assess the method's accuracy, statistical power, confidence interval coverage, and ability to have the indirect plus direct effect equal the total effect. Results demonstrated accurate estimation of the effects and relatively accurate confidence interval coverage, although in some situations the confidence interval was too narrow. Further, sample sizes needed for ample statistical power ranged from 50 (large effects) to 1000 (very small effects). Finally, the indirect plus direct effect consistently equaled the total effect, although this depended in part on the sample size. Finally, the application of MMA was based on a replication of a study wherein categorical mediators and outcomes were assessed. Using MMA, the present project reassessed the research questions using more recent data. The additional information provided by MMA sheds light on the small effect sizes of the effects of interest. This information can help interventionists and lawmakers understand where efforts and resources can make the greatest impact.

<!-- This code does not include the preliminary pages so I hard coded it -->
<!-- \hspace{10.5 cm} (\pageref{LastPage} pages) -->

\hspace{11 cm} (128 pages)


\singlespacing