---
output: pdf_document
---

\begin{quote}
\emph{Without an interpretable scale, it is difficult to use effect size to communicate results in a meaningful and useful way.}
--- Preacher and Hayes, 2011
\end{quote}

\doublespacing

# Introduction

The proposed integration of average marginal effects and mediation analysis is designed to resolve two major obstacles currently found in mediation analysis:

1. The difficulty of performing mediation analysis with categorical mediators and/or outcomes, and
2. The lack of reliable and flexible effect size estimates in mediation analysis---particularly with categorical mediators and/or outcomes.

\noindent These issues are relatively common in prevention work [e.g., @Ford2012; @Hoeppner2017; @Wong2013] and the current approaches are not adequate---as was discussed at length in the previous chapters. In this chapter, the integration of Average Marginal Effects (AMEs) and mediation analysis---*Marginal Mediation Analysis* (MMA)---is discussed, including its interpretation and assumptions as well as its benefits and limitations. It is expected that this adjustment to both the modeling and the interpretation will help researchers in the health and prevention sciences to be able to model their data in the most properly-specified way and be able to communicate their findings clearly.

# Definition of Marginal Mediation Analysis

The form of the general marginal mediation model, including the post-estimation step, are demonstrated in the following equations, where Equations \ref{equation_a} and \ref{equation_b} demonstrate the mediation estimation while Equations \ref{equation_AMEa} and \ref{equation_AMEb} show the post-estimation procedures. 
\begin{equation}\label{equation_a}
M_{ij} = a_0 + \sum_{k=1}^p a_k x_{ki} + \epsilon_i \text{ }\text{ }\text{ for j = 1, ..., m mediators}
\end{equation}
\begin{equation}\label{equation_b}
Y_{i} = \beta_0 + \sum_{j = 1}^m b_j M_{ij} + \sum_{k=1}^p c_k^{'} x_{ki} + \epsilon_i
\end{equation}
\noindent for the $ith$ individual, for $k = 1, ..., p$ predictors, and $j = 1, ..., m$ mediators. The paths are all labeled with their common term (e.g., path $a$ is labeled $a$). Combining these two equations provides the full mediation model. Using these models, we apply the post-estimation of the average marginal effects as presented by @Bartus2005. For a continuous $x_k$ variable, the average marginal effect of path $a$ is:
\begin{equation}\label{equation_AMEa}
AME^a_k = a_k \frac{1}{n} \sum_{i=1}^n f(a X)
\end{equation}
\noindent where $f$ refers to the probability density function, $a X$ is the linear combination of the predictors (i.e., the model predicted values for each observation), and $AME_k^a$ is the average marginal effect of the $a$ path for the $kth$ variable. Ultimately, Equation \ref{equation_AMEa} is identical to that of the following:
\begin{equation}\label{equation_AMEa1}
AME^a_k = \frac{1}{n} \sum_{i=1}^n \frac{f(aX_1) - f(aX_2)}{2h}
\end{equation}
\noindent where 
\begin{equation}\label{equation_AMEa2}
aX_1 = \begin{bmatrix}
ax_{11} & ax_{12} & \dots & ax_{1k} + h & \dots & ax_{1p} \\
ax_{21} & ax_{22} & \dots & ax_{2k} + h & \dots & ax_{2p} \\
\vdots  & \vdots  & \ddots & \vdots     & \ddots  & \vdots \\
ax_{n1} & ax_{n2} & \dots & ax_{nk} + h & \dots & ax_{np}
\end{bmatrix}
\end{equation}
\noindent and
\begin{equation}\label{equation_AMEa3}
aX_2 = \begin{bmatrix}
ax_{11} & ax_{12} & \dots & ax_{1k} - h & \dots & ax_{1p} \\
ax_{21} & ax_{22} & \dots & ax_{2k} - h & \dots & ax_{2p} \\
\vdots  & \vdots  & \ddots & \vdots     & \ddots  & \vdots \\
ax_{n1} & ax_{n2} & \dots & ax_{nk} - h & \dots & ax_{np}
\end{bmatrix}
\end{equation}
\noindent Both $f(aX_1)$ and $f(aX_2)$ are the model predicted value for the outcome given the small change due to $h$. Equations \ref{equation_AMEa1}, \ref{equation_AMEa2}, and \ref{equation_AMEa3} use a very small $h$ value (default is $1 \times 10^{-7}$). This provides the change in the average predicted value for a very small increase and a very small decrease in in the $x_k$ variable. This is also described in depth by @Leeper2017 since it is the strategy employed by `margins`. This approach is flexible---especially in the R statistical environment with the improvement of derivative computation that Leeper provided. 

Similarly, the AME of a dummy coded variable in the $a$ path is:
\begin{equation}\label{equation_AMEb}
AME_{k}^a = \frac{1}{n} \sum_{i=1}^{n} \big[ F(a X | x_{ki} = 1) - F(a X | x_{ki} = 0) \big]
\end{equation}
\noindent where $F(a X | x_{ki} = 1)$ is the predicted value of the $ith$ observation when the dummy variable equals one and $F(a X | x_{ki} = 0)$ is the predicted value when the dummy value equals zero. This is the same approach used by `margins`.

Notably, these same post-estimation equations (\ref{equation_AMEa} and \ref{equation_AMEb}) can be used for the $b$ and $c'$ paths as well. 

# Interpretation

The interpretation of Marginal Mediation is based on the original units of the mediator(s) and outcome(s). Because there are so many possible combinations of GLM types within mediation analysis, instead of outlining every combination, the basic principles are presented that apply to all situations.

## Principle 1: The individual paths are interpreted based on the corresponding endogenous variable's original metric.
The individual paths have interpretations identical to those of AMEs, as discussed in Chapter 2. Therefore, the $a$ path depends on the type of mediator and modeling approach chosen. For example, for a binary mediator, the $a$ path is a probability (risk); a mediator representing a count has an $a$ path that is in the same count units.


## Principle 2: The indirect effect, as a combination of the $a$ and $b$ paths, are interpreted based on the outcome's original metric.
The indirect effect is joining two paths, possibly of different metrics. However, the interpretation is still straightforward: the entire effect will be in the outcome's original metric. An example may be beneficial to highlight this principle.

Suppose there are data with a hypothesized binary mediator (depression or no depression) and a continuous outcome (quality of life). A logistic regression is used to model path $a$ and a linear regression is used for the $b$ and $c'$ paths. After calculating the AME of the paths, path $a$ is in units of risk (of depression) while path $b$ is the difference in the quality of life between depressed and not depressed individuals. By combining paths $a$ and $b$ through multiplication, we get the effect of the predictor on depression risk then what that depression risk does to quality of life; that is, the effect of the predictor on quality of life through depression.


## Principle 3: Both the direct and total effects are interpreted based on the outcome's original metric.
Similar to Principle 2, the direct and total effects are in the outcome's original units. This is intuitive given that the AME of the direct effect is in the outcome's units, and it is not combined with any other path. For the total effect, the indirect and direct effect (which are both in the same units) are added together to get the complete effect. It was expected that, as in linear regression (but that is lacking in other situations), $a \times b + c'= c$. That is, the indirect and direct effects together equals the total effect. This expectation was tested, as is described in the next chapter.

## Effect Sizes

A major advantage of this framework is the way effect sizes can be used intuitively.

> "First, virtually all effect size indices should be scaled appropriately, given the measurement and the question of interest. Without an *interpretable scale*, it is difficult to use effect size to communicate results in a meaningful and useful way.... Second, it should be emphasized that effect size estimates are themselves sample statistics and thus will almost certainly differ from their corresponding population values. Therefore, it is important to report confidence intervals for effect sizes..." [@Preacher2011, pg. 95, emphasis added].

The interpretation of MMA makes it clear that both of these aspects of proper effect size estimation and reporting are adequately represented. Of particular note, unlike many effect sizes that are only useful in certain research questions, the effect sizes produced by AMEs---and thus found in Marginal Mediation Analysis---are flexibly oriented to "be scaled appropriately" to best "communicate results in a meaningful and useful way" for a wide variety of situations. 

Additionally, @Preacher2011 continue: "it is important to develop a way to gauge the effect size of the product term $ab$ itself," (pg. 95). That is, not only does the effect size of the individual paths need to be meaningful but the product of $a \times b$ must be as well. Marginal Mediation Analysis provides this comparability as the indirect effect can be compared without problems with the direct and total effects (they are all in the same units). 


# Assumptions

The assumptions inherent in MMA are the same as those presented in Chapter 1 regarding mediation analysis. The only additional assumption regards the ability of the effect to be represented additively (i.e., can the effect be represented linearly after accounting for the marginal effect for each observation?). In linear models, this is already included as an implicit assumption. For other models, although the relationship may not be linear in the outcome, taking the average of the effects across the observations is assumed to be representative of the relationship across the sample.

# Reproducibility and Interpretability

As mentioned previously, categorical mediators/outcomes are generally not difficult to model using GLMs---only the interpretation is difficult. Generalized linear models, in conjunction with AMEs, allow researchers to use more correct functional forms, thereby reducing the justification to fit poorly specified models that have an easier interpretation. 

With this framework, MMA can be applied across the GLM spectrum and essentially any combination of GLM types. For example, a marginal mediation model is defined when the mediator is binary and the outcome is continuous; when the mediator is a count and the outcome is ordinal; when the mediator is continuous and the outcome is binary. Each has a straightforward, yet informative, interpretation as outlined by the principles above. This attribute alone can increase the reproducibility of research using mediation analysis. 

Finally, the interpretation across the paths and effects is straightforward and flexible. Other researchers, laypersons, lawmakers, and clinicians can assess the direction, magnitude, meaning, and utility of findings much easier---thus, increasing the reach and impact of research. In mediation analysis, this can prove largely beneficial given the already complex nature of the modeling scheme. By simplifying the interpretation, less cognitive resources are required to gain a basic understanding of the findings; instead, more resources can be used to understand how to apply it and assess future research questions based on the findings.



\singlespacing